name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "Checking package.json and package-lock.json sync..."
        echo "Package.json contains angular-cli-ghpages: $(grep -c 'angular-cli-ghpages' package.json || echo '0')"
        echo "Package-lock.json contains angular-cli-ghpages: $(grep -c 'angular-cli-ghpages' package-lock.json || echo '0')"
        
        # Try npm ci first, fallback to npm install if it fails
        if ! npm ci --verbose; then
          echo "npm ci failed, trying npm install..."
          npm install --verbose
        fi
        
        echo "Dependencies installed successfully"
      
    - name: Run tests
      run: |
        echo "Running tests..."
        npm run test:ci
        echo "Tests completed successfully"
      
    - name: Build for GitHub Pages
      run: |
        echo "Building for GitHub Pages..."
        npm run build:github
        echo "Build completed successfully"
        ls -la dist/strive/
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist/strive'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
